// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_interface.proto

package routing;

public final class MsgInterface {
  private MsgInterface() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RouteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Route)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * a node should not have a value though this is not enforced
     * </pre>
     *
     * <code>required int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <pre>
     * a node should not have a value though this is not enforced
     * </pre>
     *
     * <code>required int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>required .Route.Path path = 2;</code>
     */
    boolean hasPath();
    /**
     * <code>required .Route.Path path = 2;</code>
     */
    routing.MsgInterface.Route.Path getPath();
  }
  /**
   * Protobuf type {@code Route}
   */
  public  static final class Route extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Route)
      RouteOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Route.newBuilder() to construct.
    private Route(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Route() {
      id_ = 0L;
      path_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Route(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              routing.MsgInterface.Route.Path value = routing.MsgInterface.Route.Path.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                path_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return routing.MsgInterface.internal_static_Route_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return routing.MsgInterface.internal_static_Route_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              routing.MsgInterface.Route.class, routing.MsgInterface.Route.Builder.class);
    }

    /**
     * Protobuf enum {@code Route.Path}
     */
    public enum Path
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NETWORK_DISCOVERY = 0;</code>
       */
      NETWORK_DISCOVERY(0),
      /**
       * <code>NETWORK_DISCOVERY_RESPONSE = 1;</code>
       */
      NETWORK_DISCOVERY_RESPONSE(1),
      /**
       * <pre>
       *for future use
       * </pre>
       *
       * <code>USER = 2;</code>
       */
      USER(2),
      /**
       * <pre>
       *for future use
       * </pre>
       *
       * <code>MESSAGE = 3;</code>
       */
      MESSAGE(3),
      /**
       * <pre>
       *for future use
       * </pre>
       *
       * <code>GROUP = 4;</code>
       */
      GROUP(4),
      /**
       * <pre>
       *example
       * </pre>
       *
       * <code>PING = 5;</code>
       */
      PING(5),
      ;

      /**
       * <code>NETWORK_DISCOVERY = 0;</code>
       */
      public static final int NETWORK_DISCOVERY_VALUE = 0;
      /**
       * <code>NETWORK_DISCOVERY_RESPONSE = 1;</code>
       */
      public static final int NETWORK_DISCOVERY_RESPONSE_VALUE = 1;
      /**
       * <pre>
       *for future use
       * </pre>
       *
       * <code>USER = 2;</code>
       */
      public static final int USER_VALUE = 2;
      /**
       * <pre>
       *for future use
       * </pre>
       *
       * <code>MESSAGE = 3;</code>
       */
      public static final int MESSAGE_VALUE = 3;
      /**
       * <pre>
       *for future use
       * </pre>
       *
       * <code>GROUP = 4;</code>
       */
      public static final int GROUP_VALUE = 4;
      /**
       * <pre>
       *example
       * </pre>
       *
       * <code>PING = 5;</code>
       */
      public static final int PING_VALUE = 5;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Path valueOf(int value) {
        return forNumber(value);
      }

      public static Path forNumber(int value) {
        switch (value) {
          case 0: return NETWORK_DISCOVERY;
          case 1: return NETWORK_DISCOVERY_RESPONSE;
          case 2: return USER;
          case 3: return MESSAGE;
          case 4: return GROUP;
          case 5: return PING;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Path>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Path> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Path>() {
              public Path findValueByNumber(int number) {
                return Path.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return routing.MsgInterface.Route.getDescriptor().getEnumTypes().get(0);
      }

      private static final Path[] VALUES = values();

      public static Path valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Path(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Route.Path)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     * a node should not have a value though this is not enforced
     * </pre>
     *
     * <code>required int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * a node should not have a value though this is not enforced
     * </pre>
     *
     * <code>required int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int PATH_FIELD_NUMBER = 2;
    private int path_;
    /**
     * <code>required .Route.Path path = 2;</code>
     */
    public boolean hasPath() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .Route.Path path = 2;</code>
     */
    public routing.MsgInterface.Route.Path getPath() {
      routing.MsgInterface.Route.Path result = routing.MsgInterface.Route.Path.valueOf(path_);
      return result == null ? routing.MsgInterface.Route.Path.NETWORK_DISCOVERY : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPath()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, path_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, path_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof routing.MsgInterface.Route)) {
        return super.equals(obj);
      }
      routing.MsgInterface.Route other = (routing.MsgInterface.Route) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasPath() == other.hasPath());
      if (hasPath()) {
        result = result && path_ == other.path_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
      }
      if (hasPath()) {
        hash = (37 * hash) + PATH_FIELD_NUMBER;
        hash = (53 * hash) + path_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static routing.MsgInterface.Route parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static routing.MsgInterface.Route parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static routing.MsgInterface.Route parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static routing.MsgInterface.Route parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static routing.MsgInterface.Route parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static routing.MsgInterface.Route parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static routing.MsgInterface.Route parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static routing.MsgInterface.Route parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static routing.MsgInterface.Route parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static routing.MsgInterface.Route parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static routing.MsgInterface.Route parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static routing.MsgInterface.Route parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(routing.MsgInterface.Route prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Route}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Route)
        routing.MsgInterface.RouteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return routing.MsgInterface.internal_static_Route_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return routing.MsgInterface.internal_static_Route_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                routing.MsgInterface.Route.class, routing.MsgInterface.Route.Builder.class);
      }

      // Construct using routing.MsgInterface.Route.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        path_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return routing.MsgInterface.internal_static_Route_descriptor;
      }

      public routing.MsgInterface.Route getDefaultInstanceForType() {
        return routing.MsgInterface.Route.getDefaultInstance();
      }

      public routing.MsgInterface.Route build() {
        routing.MsgInterface.Route result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public routing.MsgInterface.Route buildPartial() {
        routing.MsgInterface.Route result = new routing.MsgInterface.Route(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.path_ = path_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof routing.MsgInterface.Route) {
          return mergeFrom((routing.MsgInterface.Route)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(routing.MsgInterface.Route other) {
        if (other == routing.MsgInterface.Route.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasPath()) {
          setPath(other.getPath());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasPath()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        routing.MsgInterface.Route parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (routing.MsgInterface.Route) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <pre>
       * a node should not have a value though this is not enforced
       * </pre>
       *
       * <code>required int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * a node should not have a value though this is not enforced
       * </pre>
       *
       * <code>required int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       * a node should not have a value though this is not enforced
       * </pre>
       *
       * <code>required int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * a node should not have a value though this is not enforced
       * </pre>
       *
       * <code>required int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private int path_ = 0;
      /**
       * <code>required .Route.Path path = 2;</code>
       */
      public boolean hasPath() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .Route.Path path = 2;</code>
       */
      public routing.MsgInterface.Route.Path getPath() {
        routing.MsgInterface.Route.Path result = routing.MsgInterface.Route.Path.valueOf(path_);
        return result == null ? routing.MsgInterface.Route.Path.NETWORK_DISCOVERY : result;
      }
      /**
       * <code>required .Route.Path path = 2;</code>
       */
      public Builder setPath(routing.MsgInterface.Route.Path value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        path_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .Route.Path path = 2;</code>
       */
      public Builder clearPath() {
        bitField0_ = (bitField0_ & ~0x00000002);
        path_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Route)
    }

    // @@protoc_insertion_point(class_scope:Route)
    private static final routing.MsgInterface.Route DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new routing.MsgInterface.Route();
    }

    public static routing.MsgInterface.Route getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Route>
        PARSER = new com.google.protobuf.AbstractParser<Route>() {
      public Route parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Route(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Route> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Route> getParserForType() {
      return PARSER;
    }

    public routing.MsgInterface.Route getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NetworkDiscoveryPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NetworkDiscoveryPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *If sender is a server node, then this field can contain its group id. If sender is end user client, then this field is not required.
     * </pre>
     *
     * <code>optional string group = 1;</code>
     */
    boolean hasGroup();
    /**
     * <pre>
     *If sender is a server node, then this field can contain its group id. If sender is end user client, then this field is not required.
     * </pre>
     *
     * <code>optional string group = 1;</code>
     */
    java.lang.String getGroup();
    /**
     * <pre>
     *If sender is a server node, then this field can contain its group id. If sender is end user client, then this field is not required.
     * </pre>
     *
     * <code>optional string group = 1;</code>
     */
    com.google.protobuf.ByteString
        getGroupBytes();

    /**
     * <pre>
     *node id of the sender
     * </pre>
     *
     * <code>required string nodeid = 2;</code>
     */
    boolean hasNodeid();
    /**
     * <pre>
     *node id of the sender
     * </pre>
     *
     * <code>required string nodeid = 2;</code>
     */
    java.lang.String getNodeid();
    /**
     * <pre>
     *node id of the sender
     * </pre>
     *
     * <code>required string nodeid = 2;</code>
     */
    com.google.protobuf.ByteString
        getNodeidBytes();

    /**
     * <code>required .NetworkDiscoveryPacket.Sender sender = 3 [default = SERVER_NODE];</code>
     */
    boolean hasSender();
    /**
     * <code>required .NetworkDiscoveryPacket.Sender sender = 3 [default = SERVER_NODE];</code>
     */
    routing.MsgInterface.NetworkDiscoveryPacket.Sender getSender();
  }
  /**
   * Protobuf type {@code NetworkDiscoveryPacket}
   */
  public  static final class NetworkDiscoveryPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NetworkDiscoveryPacket)
      NetworkDiscoveryPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NetworkDiscoveryPacket.newBuilder() to construct.
    private NetworkDiscoveryPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NetworkDiscoveryPacket() {
      group_ = "";
      nodeid_ = "";
      sender_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NetworkDiscoveryPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              group_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              nodeid_ = bs;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              routing.MsgInterface.NetworkDiscoveryPacket.Sender value = routing.MsgInterface.NetworkDiscoveryPacket.Sender.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                sender_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return routing.MsgInterface.internal_static_NetworkDiscoveryPacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return routing.MsgInterface.internal_static_NetworkDiscoveryPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              routing.MsgInterface.NetworkDiscoveryPacket.class, routing.MsgInterface.NetworkDiscoveryPacket.Builder.class);
    }

    /**
     * Protobuf enum {@code NetworkDiscoveryPacket.Sender}
     */
    public enum Sender
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SERVER_NODE = 0;</code>
       */
      SERVER_NODE(0),
      /**
       * <code>END_USER_CLIENT = 1;</code>
       */
      END_USER_CLIENT(1),
      ;

      /**
       * <code>SERVER_NODE = 0;</code>
       */
      public static final int SERVER_NODE_VALUE = 0;
      /**
       * <code>END_USER_CLIENT = 1;</code>
       */
      public static final int END_USER_CLIENT_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Sender valueOf(int value) {
        return forNumber(value);
      }

      public static Sender forNumber(int value) {
        switch (value) {
          case 0: return SERVER_NODE;
          case 1: return END_USER_CLIENT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Sender>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Sender> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Sender>() {
              public Sender findValueByNumber(int number) {
                return Sender.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return routing.MsgInterface.NetworkDiscoveryPacket.getDescriptor().getEnumTypes().get(0);
      }

      private static final Sender[] VALUES = values();

      public static Sender valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Sender(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:NetworkDiscoveryPacket.Sender)
    }

    private int bitField0_;
    public static final int GROUP_FIELD_NUMBER = 1;
    private volatile java.lang.Object group_;
    /**
     * <pre>
     *If sender is a server node, then this field can contain its group id. If sender is end user client, then this field is not required.
     * </pre>
     *
     * <code>optional string group = 1;</code>
     */
    public boolean hasGroup() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *If sender is a server node, then this field can contain its group id. If sender is end user client, then this field is not required.
     * </pre>
     *
     * <code>optional string group = 1;</code>
     */
    public java.lang.String getGroup() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          group_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *If sender is a server node, then this field can contain its group id. If sender is end user client, then this field is not required.
     * </pre>
     *
     * <code>optional string group = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGroupBytes() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NODEID_FIELD_NUMBER = 2;
    private volatile java.lang.Object nodeid_;
    /**
     * <pre>
     *node id of the sender
     * </pre>
     *
     * <code>required string nodeid = 2;</code>
     */
    public boolean hasNodeid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *node id of the sender
     * </pre>
     *
     * <code>required string nodeid = 2;</code>
     */
    public java.lang.String getNodeid() {
      java.lang.Object ref = nodeid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nodeid_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *node id of the sender
     * </pre>
     *
     * <code>required string nodeid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNodeidBytes() {
      java.lang.Object ref = nodeid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDER_FIELD_NUMBER = 3;
    private int sender_;
    /**
     * <code>required .NetworkDiscoveryPacket.Sender sender = 3 [default = SERVER_NODE];</code>
     */
    public boolean hasSender() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .NetworkDiscoveryPacket.Sender sender = 3 [default = SERVER_NODE];</code>
     */
    public routing.MsgInterface.NetworkDiscoveryPacket.Sender getSender() {
      routing.MsgInterface.NetworkDiscoveryPacket.Sender result = routing.MsgInterface.NetworkDiscoveryPacket.Sender.valueOf(sender_);
      return result == null ? routing.MsgInterface.NetworkDiscoveryPacket.Sender.SERVER_NODE : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasNodeid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSender()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, group_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nodeid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, sender_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, group_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nodeid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, sender_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof routing.MsgInterface.NetworkDiscoveryPacket)) {
        return super.equals(obj);
      }
      routing.MsgInterface.NetworkDiscoveryPacket other = (routing.MsgInterface.NetworkDiscoveryPacket) obj;

      boolean result = true;
      result = result && (hasGroup() == other.hasGroup());
      if (hasGroup()) {
        result = result && getGroup()
            .equals(other.getGroup());
      }
      result = result && (hasNodeid() == other.hasNodeid());
      if (hasNodeid()) {
        result = result && getNodeid()
            .equals(other.getNodeid());
      }
      result = result && (hasSender() == other.hasSender());
      if (hasSender()) {
        result = result && sender_ == other.sender_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasGroup()) {
        hash = (37 * hash) + GROUP_FIELD_NUMBER;
        hash = (53 * hash) + getGroup().hashCode();
      }
      if (hasNodeid()) {
        hash = (37 * hash) + NODEID_FIELD_NUMBER;
        hash = (53 * hash) + getNodeid().hashCode();
      }
      if (hasSender()) {
        hash = (37 * hash) + SENDER_FIELD_NUMBER;
        hash = (53 * hash) + sender_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static routing.MsgInterface.NetworkDiscoveryPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static routing.MsgInterface.NetworkDiscoveryPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static routing.MsgInterface.NetworkDiscoveryPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static routing.MsgInterface.NetworkDiscoveryPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static routing.MsgInterface.NetworkDiscoveryPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static routing.MsgInterface.NetworkDiscoveryPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static routing.MsgInterface.NetworkDiscoveryPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static routing.MsgInterface.NetworkDiscoveryPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static routing.MsgInterface.NetworkDiscoveryPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static routing.MsgInterface.NetworkDiscoveryPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static routing.MsgInterface.NetworkDiscoveryPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static routing.MsgInterface.NetworkDiscoveryPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(routing.MsgInterface.NetworkDiscoveryPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NetworkDiscoveryPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NetworkDiscoveryPacket)
        routing.MsgInterface.NetworkDiscoveryPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return routing.MsgInterface.internal_static_NetworkDiscoveryPacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return routing.MsgInterface.internal_static_NetworkDiscoveryPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                routing.MsgInterface.NetworkDiscoveryPacket.class, routing.MsgInterface.NetworkDiscoveryPacket.Builder.class);
      }

      // Construct using routing.MsgInterface.NetworkDiscoveryPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        group_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        nodeid_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        sender_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return routing.MsgInterface.internal_static_NetworkDiscoveryPacket_descriptor;
      }

      public routing.MsgInterface.NetworkDiscoveryPacket getDefaultInstanceForType() {
        return routing.MsgInterface.NetworkDiscoveryPacket.getDefaultInstance();
      }

      public routing.MsgInterface.NetworkDiscoveryPacket build() {
        routing.MsgInterface.NetworkDiscoveryPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public routing.MsgInterface.NetworkDiscoveryPacket buildPartial() {
        routing.MsgInterface.NetworkDiscoveryPacket result = new routing.MsgInterface.NetworkDiscoveryPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.group_ = group_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nodeid_ = nodeid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sender_ = sender_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof routing.MsgInterface.NetworkDiscoveryPacket) {
          return mergeFrom((routing.MsgInterface.NetworkDiscoveryPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(routing.MsgInterface.NetworkDiscoveryPacket other) {
        if (other == routing.MsgInterface.NetworkDiscoveryPacket.getDefaultInstance()) return this;
        if (other.hasGroup()) {
          bitField0_ |= 0x00000001;
          group_ = other.group_;
          onChanged();
        }
        if (other.hasNodeid()) {
          bitField0_ |= 0x00000002;
          nodeid_ = other.nodeid_;
          onChanged();
        }
        if (other.hasSender()) {
          setSender(other.getSender());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNodeid()) {
          return false;
        }
        if (!hasSender()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        routing.MsgInterface.NetworkDiscoveryPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (routing.MsgInterface.NetworkDiscoveryPacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object group_ = "";
      /**
       * <pre>
       *If sender is a server node, then this field can contain its group id. If sender is end user client, then this field is not required.
       * </pre>
       *
       * <code>optional string group = 1;</code>
       */
      public boolean hasGroup() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *If sender is a server node, then this field can contain its group id. If sender is end user client, then this field is not required.
       * </pre>
       *
       * <code>optional string group = 1;</code>
       */
      public java.lang.String getGroup() {
        java.lang.Object ref = group_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            group_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *If sender is a server node, then this field can contain its group id. If sender is end user client, then this field is not required.
       * </pre>
       *
       * <code>optional string group = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGroupBytes() {
        java.lang.Object ref = group_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          group_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *If sender is a server node, then this field can contain its group id. If sender is end user client, then this field is not required.
       * </pre>
       *
       * <code>optional string group = 1;</code>
       */
      public Builder setGroup(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        group_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *If sender is a server node, then this field can contain its group id. If sender is end user client, then this field is not required.
       * </pre>
       *
       * <code>optional string group = 1;</code>
       */
      public Builder clearGroup() {
        bitField0_ = (bitField0_ & ~0x00000001);
        group_ = getDefaultInstance().getGroup();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *If sender is a server node, then this field can contain its group id. If sender is end user client, then this field is not required.
       * </pre>
       *
       * <code>optional string group = 1;</code>
       */
      public Builder setGroupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        group_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nodeid_ = "";
      /**
       * <pre>
       *node id of the sender
       * </pre>
       *
       * <code>required string nodeid = 2;</code>
       */
      public boolean hasNodeid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *node id of the sender
       * </pre>
       *
       * <code>required string nodeid = 2;</code>
       */
      public java.lang.String getNodeid() {
        java.lang.Object ref = nodeid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nodeid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *node id of the sender
       * </pre>
       *
       * <code>required string nodeid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNodeidBytes() {
        java.lang.Object ref = nodeid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *node id of the sender
       * </pre>
       *
       * <code>required string nodeid = 2;</code>
       */
      public Builder setNodeid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nodeid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *node id of the sender
       * </pre>
       *
       * <code>required string nodeid = 2;</code>
       */
      public Builder clearNodeid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nodeid_ = getDefaultInstance().getNodeid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *node id of the sender
       * </pre>
       *
       * <code>required string nodeid = 2;</code>
       */
      public Builder setNodeidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nodeid_ = value;
        onChanged();
        return this;
      }

      private int sender_ = 0;
      /**
       * <code>required .NetworkDiscoveryPacket.Sender sender = 3 [default = SERVER_NODE];</code>
       */
      public boolean hasSender() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .NetworkDiscoveryPacket.Sender sender = 3 [default = SERVER_NODE];</code>
       */
      public routing.MsgInterface.NetworkDiscoveryPacket.Sender getSender() {
        routing.MsgInterface.NetworkDiscoveryPacket.Sender result = routing.MsgInterface.NetworkDiscoveryPacket.Sender.valueOf(sender_);
        return result == null ? routing.MsgInterface.NetworkDiscoveryPacket.Sender.SERVER_NODE : result;
      }
      /**
       * <code>required .NetworkDiscoveryPacket.Sender sender = 3 [default = SERVER_NODE];</code>
       */
      public Builder setSender(routing.MsgInterface.NetworkDiscoveryPacket.Sender value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        sender_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .NetworkDiscoveryPacket.Sender sender = 3 [default = SERVER_NODE];</code>
       */
      public Builder clearSender() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sender_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NetworkDiscoveryPacket)
    }

    // @@protoc_insertion_point(class_scope:NetworkDiscoveryPacket)
    private static final routing.MsgInterface.NetworkDiscoveryPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new routing.MsgInterface.NetworkDiscoveryPacket();
    }

    public static routing.MsgInterface.NetworkDiscoveryPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<NetworkDiscoveryPacket>
        PARSER = new com.google.protobuf.AbstractParser<NetworkDiscoveryPacket>() {
      public NetworkDiscoveryPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NetworkDiscoveryPacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NetworkDiscoveryPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NetworkDiscoveryPacket> getParserForType() {
      return PARSER;
    }

    public routing.MsgInterface.NetworkDiscoveryPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ServerNodeDiscoveryResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ServerNodeDiscoveryResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string group = 1;</code>
     */
    boolean hasGroup();
    /**
     * <code>required string group = 1;</code>
     */
    java.lang.String getGroup();
    /**
     * <code>required string group = 1;</code>
     */
    com.google.protobuf.ByteString
        getGroupBytes();

    /**
     * <code>required string ip = 2;</code>
     */
    boolean hasIp();
    /**
     * <code>required string ip = 2;</code>
     */
    java.lang.String getIp();
    /**
     * <code>required string ip = 2;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>required string nodeid = 3;</code>
     */
    boolean hasNodeid();
    /**
     * <code>required string nodeid = 3;</code>
     */
    java.lang.String getNodeid();
    /**
     * <code>required string nodeid = 3;</code>
     */
    com.google.protobuf.ByteString
        getNodeidBytes();
  }
  /**
   * Protobuf type {@code ServerNodeDiscoveryResponse}
   */
  public  static final class ServerNodeDiscoveryResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ServerNodeDiscoveryResponse)
      ServerNodeDiscoveryResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServerNodeDiscoveryResponse.newBuilder() to construct.
    private ServerNodeDiscoveryResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServerNodeDiscoveryResponse() {
      group_ = "";
      ip_ = "";
      nodeid_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServerNodeDiscoveryResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              group_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              ip_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              nodeid_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return routing.MsgInterface.internal_static_ServerNodeDiscoveryResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return routing.MsgInterface.internal_static_ServerNodeDiscoveryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              routing.MsgInterface.ServerNodeDiscoveryResponse.class, routing.MsgInterface.ServerNodeDiscoveryResponse.Builder.class);
    }

    private int bitField0_;
    public static final int GROUP_FIELD_NUMBER = 1;
    private volatile java.lang.Object group_;
    /**
     * <code>required string group = 1;</code>
     */
    public boolean hasGroup() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string group = 1;</code>
     */
    public java.lang.String getGroup() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          group_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string group = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGroupBytes() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 2;
    private volatile java.lang.Object ip_;
    /**
     * <code>required string ip = 2;</code>
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string ip = 2;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ip_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ip = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NODEID_FIELD_NUMBER = 3;
    private volatile java.lang.Object nodeid_;
    /**
     * <code>required string nodeid = 3;</code>
     */
    public boolean hasNodeid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string nodeid = 3;</code>
     */
    public java.lang.String getNodeid() {
      java.lang.Object ref = nodeid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nodeid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string nodeid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNodeidBytes() {
      java.lang.Object ref = nodeid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasGroup()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNodeid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, group_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ip_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nodeid_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, group_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ip_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nodeid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof routing.MsgInterface.ServerNodeDiscoveryResponse)) {
        return super.equals(obj);
      }
      routing.MsgInterface.ServerNodeDiscoveryResponse other = (routing.MsgInterface.ServerNodeDiscoveryResponse) obj;

      boolean result = true;
      result = result && (hasGroup() == other.hasGroup());
      if (hasGroup()) {
        result = result && getGroup()
            .equals(other.getGroup());
      }
      result = result && (hasIp() == other.hasIp());
      if (hasIp()) {
        result = result && getIp()
            .equals(other.getIp());
      }
      result = result && (hasNodeid() == other.hasNodeid());
      if (hasNodeid()) {
        result = result && getNodeid()
            .equals(other.getNodeid());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasGroup()) {
        hash = (37 * hash) + GROUP_FIELD_NUMBER;
        hash = (53 * hash) + getGroup().hashCode();
      }
      if (hasIp()) {
        hash = (37 * hash) + IP_FIELD_NUMBER;
        hash = (53 * hash) + getIp().hashCode();
      }
      if (hasNodeid()) {
        hash = (37 * hash) + NODEID_FIELD_NUMBER;
        hash = (53 * hash) + getNodeid().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static routing.MsgInterface.ServerNodeDiscoveryResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static routing.MsgInterface.ServerNodeDiscoveryResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static routing.MsgInterface.ServerNodeDiscoveryResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static routing.MsgInterface.ServerNodeDiscoveryResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static routing.MsgInterface.ServerNodeDiscoveryResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static routing.MsgInterface.ServerNodeDiscoveryResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static routing.MsgInterface.ServerNodeDiscoveryResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static routing.MsgInterface.ServerNodeDiscoveryResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static routing.MsgInterface.ServerNodeDiscoveryResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static routing.MsgInterface.ServerNodeDiscoveryResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static routing.MsgInterface.ServerNodeDiscoveryResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static routing.MsgInterface.ServerNodeDiscoveryResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(routing.MsgInterface.ServerNodeDiscoveryResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ServerNodeDiscoveryResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ServerNodeDiscoveryResponse)
        routing.MsgInterface.ServerNodeDiscoveryResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return routing.MsgInterface.internal_static_ServerNodeDiscoveryResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return routing.MsgInterface.internal_static_ServerNodeDiscoveryResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                routing.MsgInterface.ServerNodeDiscoveryResponse.class, routing.MsgInterface.ServerNodeDiscoveryResponse.Builder.class);
      }

      // Construct using routing.MsgInterface.ServerNodeDiscoveryResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        group_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        nodeid_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return routing.MsgInterface.internal_static_ServerNodeDiscoveryResponse_descriptor;
      }

      public routing.MsgInterface.ServerNodeDiscoveryResponse getDefaultInstanceForType() {
        return routing.MsgInterface.ServerNodeDiscoveryResponse.getDefaultInstance();
      }

      public routing.MsgInterface.ServerNodeDiscoveryResponse build() {
        routing.MsgInterface.ServerNodeDiscoveryResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public routing.MsgInterface.ServerNodeDiscoveryResponse buildPartial() {
        routing.MsgInterface.ServerNodeDiscoveryResponse result = new routing.MsgInterface.ServerNodeDiscoveryResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.group_ = group_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ip_ = ip_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.nodeid_ = nodeid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof routing.MsgInterface.ServerNodeDiscoveryResponse) {
          return mergeFrom((routing.MsgInterface.ServerNodeDiscoveryResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(routing.MsgInterface.ServerNodeDiscoveryResponse other) {
        if (other == routing.MsgInterface.ServerNodeDiscoveryResponse.getDefaultInstance()) return this;
        if (other.hasGroup()) {
          bitField0_ |= 0x00000001;
          group_ = other.group_;
          onChanged();
        }
        if (other.hasIp()) {
          bitField0_ |= 0x00000002;
          ip_ = other.ip_;
          onChanged();
        }
        if (other.hasNodeid()) {
          bitField0_ |= 0x00000004;
          nodeid_ = other.nodeid_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasGroup()) {
          return false;
        }
        if (!hasIp()) {
          return false;
        }
        if (!hasNodeid()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        routing.MsgInterface.ServerNodeDiscoveryResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (routing.MsgInterface.ServerNodeDiscoveryResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object group_ = "";
      /**
       * <code>required string group = 1;</code>
       */
      public boolean hasGroup() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string group = 1;</code>
       */
      public java.lang.String getGroup() {
        java.lang.Object ref = group_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            group_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string group = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGroupBytes() {
        java.lang.Object ref = group_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          group_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string group = 1;</code>
       */
      public Builder setGroup(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        group_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string group = 1;</code>
       */
      public Builder clearGroup() {
        bitField0_ = (bitField0_ & ~0x00000001);
        group_ = getDefaultInstance().getGroup();
        onChanged();
        return this;
      }
      /**
       * <code>required string group = 1;</code>
       */
      public Builder setGroupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        group_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>required string ip = 2;</code>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string ip = 2;</code>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ip_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ip = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ip = 2;</code>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ip = 2;</code>
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>required string ip = 2;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ip_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nodeid_ = "";
      /**
       * <code>required string nodeid = 3;</code>
       */
      public boolean hasNodeid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string nodeid = 3;</code>
       */
      public java.lang.String getNodeid() {
        java.lang.Object ref = nodeid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nodeid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string nodeid = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNodeidBytes() {
        java.lang.Object ref = nodeid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string nodeid = 3;</code>
       */
      public Builder setNodeid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        nodeid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string nodeid = 3;</code>
       */
      public Builder clearNodeid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        nodeid_ = getDefaultInstance().getNodeid();
        onChanged();
        return this;
      }
      /**
       * <code>required string nodeid = 3;</code>
       */
      public Builder setNodeidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        nodeid_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ServerNodeDiscoveryResponse)
    }

    // @@protoc_insertion_point(class_scope:ServerNodeDiscoveryResponse)
    private static final routing.MsgInterface.ServerNodeDiscoveryResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new routing.MsgInterface.ServerNodeDiscoveryResponse();
    }

    public static routing.MsgInterface.ServerNodeDiscoveryResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ServerNodeDiscoveryResponse>
        PARSER = new com.google.protobuf.AbstractParser<ServerNodeDiscoveryResponse>() {
      public ServerNodeDiscoveryResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ServerNodeDiscoveryResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServerNodeDiscoveryResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServerNodeDiscoveryResponse> getParserForType() {
      return PARSER;
    }

    public routing.MsgInterface.ServerNodeDiscoveryResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Route_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Route_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NetworkDiscoveryPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NetworkDiscoveryPacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerNodeDiscoveryResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServerNodeDiscoveryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023msg_interface.proto\"\231\001\n\005Route\022\n\n\002id\030\001 " +
      "\002(\003\022\031\n\004path\030\002 \002(\0162\013.Route.Path\"i\n\004Path\022\025" +
      "\n\021NETWORK_DISCOVERY\020\000\022\036\n\032NETWORK_DISCOVE" +
      "RY_RESPONSE\020\001\022\010\n\004USER\020\002\022\013\n\007MESSAGE\020\003\022\t\n\005" +
      "GROUP\020\004\022\010\n\004PING\020\005\"\244\001\n\026NetworkDiscoveryPa" +
      "cket\022\r\n\005group\030\001 \001(\t\022\016\n\006nodeid\030\002 \002(\t\022;\n\006s" +
      "ender\030\003 \002(\0162\036.NetworkDiscoveryPacket.Sen" +
      "der:\013SERVER_NODE\".\n\006Sender\022\017\n\013SERVER_NOD" +
      "E\020\000\022\023\n\017END_USER_CLIENT\020\001\"H\n\033ServerNodeDi" +
      "scoveryResponse\022\r\n\005group\030\001 \002(\t\022\n\n\002ip\030\002 \002",
      "(\t\022\016\n\006nodeid\030\003 \002(\tB\013\n\007routingH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Route_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Route_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Route_descriptor,
        new java.lang.String[] { "Id", "Path", });
    internal_static_NetworkDiscoveryPacket_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_NetworkDiscoveryPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NetworkDiscoveryPacket_descriptor,
        new java.lang.String[] { "Group", "Nodeid", "Sender", });
    internal_static_ServerNodeDiscoveryResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ServerNodeDiscoveryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServerNodeDiscoveryResponse_descriptor,
        new java.lang.String[] { "Group", "Ip", "Nodeid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
